#ifndef CONSTS_H
#define CONSTS_H

// Constants
#define TRACK 15.8f
#define SPEED 0.2f
#define SERVOMOTOR_ANGLE_SHIFT (-30)
#define SERVOMOTOR_ROTATE_SPEED 2.5f
#define SERVOMOTOR_ROTATE_ANGLE 40.0f
#define MAX_FIRST_BOTTLE_DISTANCE 20.0f
#define MAX_BOTTLE_DISTANCE 30.0f
#define MOTOR_R_SPEED 255
#define MOTOR_L_SPEED 255
#define MOTOR_ROTATE_SHIFT 1.03f

// Pins
#define BUTTON_PIN 2

#define INFRARED_PIN 3

#define MOTOR_R_CONTROL1_PIN 4
#define MOTOR_R_CONTROL2_PIN 5
#define MOTOR_L_CONTROL1_PIN 10
#define MOTOR_L_CONTROL2_PIN 7
#define MOTOR_R_SPEED_PIN 11
#define MOTOR_L_SPEED_PIN 6

#define SERVOMOTOR_PIN 9

#define ULTRASONIC_TRIGGER_PIN 12
#define ULTRASONIC_ECHO_PIN 13

#endif
